name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main  # Change to your deployment branch ########################################

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}


      # - name: Transfer Build to VPS
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: '54.159.228.215'
      #     username: 'ubuntu'
      #     key: ${{ secrets.VPS_SSH_KEY }}
      #     port: 22
      #     script: |
      #       mkdir -p next-js-app
      #       cd next-js-app
      #       rsync -avz --delete-after .next package.json package-lock.json .


      - name: Add EC2 host to known hosts
        env:
          VPS_HOST: "54.159.228.215"
        run: |
          ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts


      - name: Transfer Build to VPS 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_USER: "ubuntu"
          VPS_HOST: "54.159.228.215"
          VPS_PATH: "/var/www/nextjs-app"
        run: |
          ssh-keygen -R 54.159.228.215
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $VPS_USER@$VPS_HOST "sudo mkdir -p /var/www/nextjs-app"
          sudo rsync -avz --delete-after .next package.json package-lock.json $VPS_USER@$VPS_HOST:/var/www/nextjs-app/

      - name: Restart App on VPS
        env:
          VPS_USER: "ubuntu"
          VPS_HOST: "54.159.228.215"
          VPS_PATH: "/var/www/nextjs-app"
        run: 
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            cd $VPS_PATH
            npm install --omit=dev
            pm2 stop nextjs-app || true
            pm2 start "npm start" --name nextjs-app
            pm2 save 
          EOF