name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Transfer Build to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_USER: "ubuntu"
          VPS_HOST: "54.159.228.215"
          VPS_PATH: "/var/www/nextjs-app"
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "mkdir -p $VPS_PATH"
          rsync -avz --delete-after .next package.json package-lock.json $VPS_USER@$VPS_HOST:$VPS_PATH/

      - name: Restart App on VPS
        env:
          VPS_USER: "ubuntu"
          VPS_HOST: "54.159.228.215"
          VPS_PATH: "/var/www/nextjs-app"
        run: 
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
            cd $VPS_PATH
            npm install --omit=dev
            pm2 stop nextjs-app || true
            pm2 start "npm start" --name nextjs-app
            pm2 save 
          EOF